dist: trusty
sudo: required
addons:
  apt:
    sources:
      - git-core
    packages:
      - git
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
cache: yarn
install: yarn install
